/* soapStub.h
   Generated by gSOAP 2.8.30 for zapisy.h

gSOAP XML Web services tools
Copyright (C) 2000-2016, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#include <deque>
#include <list>
#include <vector>
#include <set>
#define SOAP_NAMESPACE_OF_z1	"localhost/zapisy.wsdl"

#ifndef soapStub_H
#define soapStub_H
#include "stdsoap2.h"
#if GSOAP_VERSION != 20830
# error "GSOAP VERSION 20830 MISMATCH IN GENERATED CODE VERSUS LIBRARY CODE: PLEASE REINSTALL PACKAGE"
#endif


/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Classes, Structs and Unions                                                *
 *                                                                            *
\******************************************************************************/

class z1__student;	/* zapisy.h:154 */
class z1__temat;	/* zapisy.h:157 */
class z1__termin;	/* zapisy.h:160 */
class z1__sala;	/* zapisy.h:163 */
class z1__przedmiot;	/* zapisy.h:166 */
class z1__typ;	/* zapisy.h:169 */
class z1__prowadzacy;	/* zapisy.h:172 */
struct z1__zapiszProjektResponse;	/* zapisy.h:481 */
struct z1__zapiszProjekt;	/* zapisy.h:542 */
struct z1__dodajProjektResponse;	/* zapisy.h:553 */
struct z1__dodajProjekt;	/* zapisy.h:611 */
struct z1__zapiszTerminResponse;	/* zapisy.h:622 */
struct z1__zapiszTermin;	/* zapisy.h:683 */
struct z1__dodajTerminResponse;	/* zapisy.h:694 */
struct z1__dodajTermin;	/* zapisy.h:752 */
struct z1__eksportujProjektResponse;	/* zapisy.h:763 */
struct z1__eksportujProjekt;	/* zapisy.h:822 */
struct z1__eksportujTerminResponse;	/* zapisy.h:833 */
struct z1__eksportujTermin;	/* zapisy.h:892 */
struct z1__eksportujPrzedmiotResponse;	/* zapisy.h:903 */
struct z1__eksportujPrzedmiot;	/* zapisy.h:962 */

/* zapisy.h:154 */
#ifndef SOAP_TYPE_z1__student
#define SOAP_TYPE_z1__student (14)
/* complex XSD type 'z1:student': */
class SOAP_CMAC z1__student {
      public:
        /// Required element 'imie' of XSD type 'xsd:string'
        std::string imie;
        /// Required element 'nazwisko' of XSD type 'xsd:string'
        std::string nazwisko;
        /// Required element 'index' of XSD type 'z1:nrIndex'
        std::string index;
        /// Context that manages this object
        struct soap *soap;
      public:
        /// Return unique type id SOAP_TYPE_z1__student
        virtual int soap_type(void) const { return SOAP_TYPE_z1__student; }
        /// (Re)set members to default values
        virtual void soap_default(struct soap*);
        /// Serialize object to prepare for SOAP 1.1/1.2 encoded output (or with SOAP_XML_GRAPH) by analyzing its (cyclic) structures
        virtual void soap_serialize(struct soap*) const;
        /// Output object in XML, compliant with SOAP 1.1 encoding style, return error code or SOAP_OK
        virtual int soap_put(struct soap*, const char *tag, const char *type) const;
        /// Output object in XML, with tag and optional id attribute and xsi:type, return error code or SOAP_OK
        virtual int soap_out(struct soap*, const char *tag, int id, const char *type) const;
        /// Get object from XML, compliant with SOAP 1.1 encoding style, return pointer to object or NULL on error
        virtual void *soap_get(struct soap*, const char *tag, const char *type);
        /// Get object from XML, with matching tag and type (NULL matches any tag and type), return pointer to object or NULL on error
        virtual void *soap_in(struct soap*, const char *tag, const char *type);
        /// Return a new object of type z1__student, default initialized and not managed by a soap context
        virtual z1__student *soap_alloc(void) const { return SOAP_NEW(z1__student); }
      public:
        /// Constructor with initializations
        z1__student()
        {
          soap = (struct soap *)0;
        }
        virtual ~z1__student() { }
        /// Friend allocator used by soap_new_z1__student(struct soap*, int)
        friend SOAP_FMAC1 z1__student * SOAP_FMAC2 soap_instantiate_z1__student(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* zapisy.h:157 */
#ifndef SOAP_TYPE_z1__temat
#define SOAP_TYPE_z1__temat (15)
/* complex XSD type 'z1:temat': */
class SOAP_CMAC z1__temat {
      public:
        /// Required element 'temat' of XSD type 'xsd:string'
        std::string temat;
        /// Required element 'opis' of XSD type 'xsd:string'
        std::string opis;
        /// Required element 'miejsca' of XSD type 'xsd:nonNegativeInteger'
        std::string miejsca;
        /// Required element 'wolneMiejsca' of XSD type 'xsd:nonNegativeInteger'
        std::string wolneMiejsca;
        /// Context that manages this object
        struct soap *soap;
      public:
        /// Return unique type id SOAP_TYPE_z1__temat
        virtual int soap_type(void) const { return SOAP_TYPE_z1__temat; }
        /// (Re)set members to default values
        virtual void soap_default(struct soap*);
        /// Serialize object to prepare for SOAP 1.1/1.2 encoded output (or with SOAP_XML_GRAPH) by analyzing its (cyclic) structures
        virtual void soap_serialize(struct soap*) const;
        /// Output object in XML, compliant with SOAP 1.1 encoding style, return error code or SOAP_OK
        virtual int soap_put(struct soap*, const char *tag, const char *type) const;
        /// Output object in XML, with tag and optional id attribute and xsi:type, return error code or SOAP_OK
        virtual int soap_out(struct soap*, const char *tag, int id, const char *type) const;
        /// Get object from XML, compliant with SOAP 1.1 encoding style, return pointer to object or NULL on error
        virtual void *soap_get(struct soap*, const char *tag, const char *type);
        /// Get object from XML, with matching tag and type (NULL matches any tag and type), return pointer to object or NULL on error
        virtual void *soap_in(struct soap*, const char *tag, const char *type);
        /// Return a new object of type z1__temat, default initialized and not managed by a soap context
        virtual z1__temat *soap_alloc(void) const { return SOAP_NEW(z1__temat); }
      public:
        /// Constructor with initializations
        z1__temat()
        {
          soap = (struct soap *)0;
        }
        virtual ~z1__temat() { }
        /// Friend allocator used by soap_new_z1__temat(struct soap*, int)
        friend SOAP_FMAC1 z1__temat * SOAP_FMAC2 soap_instantiate_z1__temat(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* zapisy.h:160 */
#ifndef SOAP_TYPE_z1__termin
#define SOAP_TYPE_z1__termin (16)
/* complex XSD type 'z1:termin': */
class SOAP_CMAC z1__termin {
      public:
        /// Required element 'dzien' of XSD type 'xsd:string'
        std::string dzien;
        /// Required element 'godzinaOd' of XSD type 'z1:godzina'
        std::string godzinaOd;
        /// Required element 'godzinaDo' of XSD type 'z1:godzina'
        std::string godzinaDo;
        /// Required element 'miejsca' of XSD type 'xsd:int'
        int miejsca;
        /// Context that manages this object
        struct soap *soap;
      public:
        /// Return unique type id SOAP_TYPE_z1__termin
        virtual int soap_type(void) const { return SOAP_TYPE_z1__termin; }
        /// (Re)set members to default values
        virtual void soap_default(struct soap*);
        /// Serialize object to prepare for SOAP 1.1/1.2 encoded output (or with SOAP_XML_GRAPH) by analyzing its (cyclic) structures
        virtual void soap_serialize(struct soap*) const;
        /// Output object in XML, compliant with SOAP 1.1 encoding style, return error code or SOAP_OK
        virtual int soap_put(struct soap*, const char *tag, const char *type) const;
        /// Output object in XML, with tag and optional id attribute and xsi:type, return error code or SOAP_OK
        virtual int soap_out(struct soap*, const char *tag, int id, const char *type) const;
        /// Get object from XML, compliant with SOAP 1.1 encoding style, return pointer to object or NULL on error
        virtual void *soap_get(struct soap*, const char *tag, const char *type);
        /// Get object from XML, with matching tag and type (NULL matches any tag and type), return pointer to object or NULL on error
        virtual void *soap_in(struct soap*, const char *tag, const char *type);
        /// Return a new object of type z1__termin, default initialized and not managed by a soap context
        virtual z1__termin *soap_alloc(void) const { return SOAP_NEW(z1__termin); }
      public:
        /// Constructor with initializations
        z1__termin()
        {
          miejsca = (int)0;
          soap = (struct soap *)0;
        }
        virtual ~z1__termin() { }
        /// Friend allocator used by soap_new_z1__termin(struct soap*, int)
        friend SOAP_FMAC1 z1__termin * SOAP_FMAC2 soap_instantiate_z1__termin(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* zapisy.h:163 */
#ifndef SOAP_TYPE_z1__sala
#define SOAP_TYPE_z1__sala (17)
/* complex XSD type 'z1:sala': */
class SOAP_CMAC z1__sala {
      public:
        /// Required element 'numer' of XSD type 'xsd:string'
        std::string numer;
        /// Required element 'maxMiejsc' of XSD type 'xsd:nonNegativeInteger'
        std::string maxMiejsc;
        /// Context that manages this object
        struct soap *soap;
      public:
        /// Return unique type id SOAP_TYPE_z1__sala
        virtual int soap_type(void) const { return SOAP_TYPE_z1__sala; }
        /// (Re)set members to default values
        virtual void soap_default(struct soap*);
        /// Serialize object to prepare for SOAP 1.1/1.2 encoded output (or with SOAP_XML_GRAPH) by analyzing its (cyclic) structures
        virtual void soap_serialize(struct soap*) const;
        /// Output object in XML, compliant with SOAP 1.1 encoding style, return error code or SOAP_OK
        virtual int soap_put(struct soap*, const char *tag, const char *type) const;
        /// Output object in XML, with tag and optional id attribute and xsi:type, return error code or SOAP_OK
        virtual int soap_out(struct soap*, const char *tag, int id, const char *type) const;
        /// Get object from XML, compliant with SOAP 1.1 encoding style, return pointer to object or NULL on error
        virtual void *soap_get(struct soap*, const char *tag, const char *type);
        /// Get object from XML, with matching tag and type (NULL matches any tag and type), return pointer to object or NULL on error
        virtual void *soap_in(struct soap*, const char *tag, const char *type);
        /// Return a new object of type z1__sala, default initialized and not managed by a soap context
        virtual z1__sala *soap_alloc(void) const { return SOAP_NEW(z1__sala); }
      public:
        /// Constructor with initializations
        z1__sala()
        {
          soap = (struct soap *)0;
        }
        virtual ~z1__sala() { }
        /// Friend allocator used by soap_new_z1__sala(struct soap*, int)
        friend SOAP_FMAC1 z1__sala * SOAP_FMAC2 soap_instantiate_z1__sala(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* zapisy.h:166 */
#ifndef SOAP_TYPE_z1__przedmiot
#define SOAP_TYPE_z1__przedmiot (18)
/* complex XSD type 'z1:przedmiot': */
class SOAP_CMAC z1__przedmiot {
      public:
        /// Required element 'nazwa' of XSD type 'xsd:string'
        std::string nazwa;
        /// Required element 'typ' of XSD type 'xsd:integer'
        std::string typ;
        /// Context that manages this object
        struct soap *soap;
      public:
        /// Return unique type id SOAP_TYPE_z1__przedmiot
        virtual int soap_type(void) const { return SOAP_TYPE_z1__przedmiot; }
        /// (Re)set members to default values
        virtual void soap_default(struct soap*);
        /// Serialize object to prepare for SOAP 1.1/1.2 encoded output (or with SOAP_XML_GRAPH) by analyzing its (cyclic) structures
        virtual void soap_serialize(struct soap*) const;
        /// Output object in XML, compliant with SOAP 1.1 encoding style, return error code or SOAP_OK
        virtual int soap_put(struct soap*, const char *tag, const char *type) const;
        /// Output object in XML, with tag and optional id attribute and xsi:type, return error code or SOAP_OK
        virtual int soap_out(struct soap*, const char *tag, int id, const char *type) const;
        /// Get object from XML, compliant with SOAP 1.1 encoding style, return pointer to object or NULL on error
        virtual void *soap_get(struct soap*, const char *tag, const char *type);
        /// Get object from XML, with matching tag and type (NULL matches any tag and type), return pointer to object or NULL on error
        virtual void *soap_in(struct soap*, const char *tag, const char *type);
        /// Return a new object of type z1__przedmiot, default initialized and not managed by a soap context
        virtual z1__przedmiot *soap_alloc(void) const { return SOAP_NEW(z1__przedmiot); }
      public:
        /// Constructor with initializations
        z1__przedmiot()
        {
          soap = (struct soap *)0;
        }
        virtual ~z1__przedmiot() { }
        /// Friend allocator used by soap_new_z1__przedmiot(struct soap*, int)
        friend SOAP_FMAC1 z1__przedmiot * SOAP_FMAC2 soap_instantiate_z1__przedmiot(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* zapisy.h:169 */
#ifndef SOAP_TYPE_z1__typ
#define SOAP_TYPE_z1__typ (19)
/* complex XSD type 'z1:typ': */
class SOAP_CMAC z1__typ {
      public:
        /// Required element 'id' of XSD type 'xsd:integer'
        std::string id;
        /// Required element 'opis' of XSD type 'xsd:string'
        std::string opis;
        /// Context that manages this object
        struct soap *soap;
      public:
        /// Return unique type id SOAP_TYPE_z1__typ
        virtual int soap_type(void) const { return SOAP_TYPE_z1__typ; }
        /// (Re)set members to default values
        virtual void soap_default(struct soap*);
        /// Serialize object to prepare for SOAP 1.1/1.2 encoded output (or with SOAP_XML_GRAPH) by analyzing its (cyclic) structures
        virtual void soap_serialize(struct soap*) const;
        /// Output object in XML, compliant with SOAP 1.1 encoding style, return error code or SOAP_OK
        virtual int soap_put(struct soap*, const char *tag, const char *type) const;
        /// Output object in XML, with tag and optional id attribute and xsi:type, return error code or SOAP_OK
        virtual int soap_out(struct soap*, const char *tag, int id, const char *type) const;
        /// Get object from XML, compliant with SOAP 1.1 encoding style, return pointer to object or NULL on error
        virtual void *soap_get(struct soap*, const char *tag, const char *type);
        /// Get object from XML, with matching tag and type (NULL matches any tag and type), return pointer to object or NULL on error
        virtual void *soap_in(struct soap*, const char *tag, const char *type);
        /// Return a new object of type z1__typ, default initialized and not managed by a soap context
        virtual z1__typ *soap_alloc(void) const { return SOAP_NEW(z1__typ); }
      public:
        /// Constructor with initializations
        z1__typ()
        {
          soap = (struct soap *)0;
        }
        virtual ~z1__typ() { }
        /// Friend allocator used by soap_new_z1__typ(struct soap*, int)
        friend SOAP_FMAC1 z1__typ * SOAP_FMAC2 soap_instantiate_z1__typ(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* zapisy.h:172 */
#ifndef SOAP_TYPE_z1__prowadzacy
#define SOAP_TYPE_z1__prowadzacy (20)
/* complex XSD type 'z1:prowadzacy': */
class SOAP_CMAC z1__prowadzacy {
      public:
        /// Required element 'email' of XSD type 'xsd:string'
        std::string email;
        /// Required element 'haslo' of XSD type 'xsd:string'
        std::string haslo;
        /// Context that manages this object
        struct soap *soap;
      public:
        /// Return unique type id SOAP_TYPE_z1__prowadzacy
        virtual int soap_type(void) const { return SOAP_TYPE_z1__prowadzacy; }
        /// (Re)set members to default values
        virtual void soap_default(struct soap*);
        /// Serialize object to prepare for SOAP 1.1/1.2 encoded output (or with SOAP_XML_GRAPH) by analyzing its (cyclic) structures
        virtual void soap_serialize(struct soap*) const;
        /// Output object in XML, compliant with SOAP 1.1 encoding style, return error code or SOAP_OK
        virtual int soap_put(struct soap*, const char *tag, const char *type) const;
        /// Output object in XML, with tag and optional id attribute and xsi:type, return error code or SOAP_OK
        virtual int soap_out(struct soap*, const char *tag, int id, const char *type) const;
        /// Get object from XML, compliant with SOAP 1.1 encoding style, return pointer to object or NULL on error
        virtual void *soap_get(struct soap*, const char *tag, const char *type);
        /// Get object from XML, with matching tag and type (NULL matches any tag and type), return pointer to object or NULL on error
        virtual void *soap_in(struct soap*, const char *tag, const char *type);
        /// Return a new object of type z1__prowadzacy, default initialized and not managed by a soap context
        virtual z1__prowadzacy *soap_alloc(void) const { return SOAP_NEW(z1__prowadzacy); }
      public:
        /// Constructor with initializations
        z1__prowadzacy()
        {
          soap = (struct soap *)0;
        }
        virtual ~z1__prowadzacy() { }
        /// Friend allocator used by soap_new_z1__prowadzacy(struct soap*, int)
        friend SOAP_FMAC1 z1__prowadzacy * SOAP_FMAC2 soap_instantiate_z1__prowadzacy(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* zapisy.h:481 */
#ifndef SOAP_TYPE_z1__zapiszProjektResponse
#define SOAP_TYPE_z1__zapiszProjektResponse (28)
/* complex XSD type 'z1:zapiszProjektResponse': */
struct z1__zapiszProjektResponse {
      public:
        /** Required element 'rezultat' of XSD type 'z1:wynik' */
        std::string rezultat;
      public:
        /** Return unique type id SOAP_TYPE_z1__zapiszProjektResponse */
        int soap_type() const { return SOAP_TYPE_z1__zapiszProjektResponse; }
        /** Constructor with member initializations */
        z1__zapiszProjektResponse()
        {
        }
        /** Friend allocator used by soap_new_z1__zapiszProjektResponse(struct soap*, int) */
        friend SOAP_FMAC1 z1__zapiszProjektResponse * SOAP_FMAC2 soap_instantiate_z1__zapiszProjektResponse(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* zapisy.h:542 */
#ifndef SOAP_TYPE_z1__zapiszProjekt
#define SOAP_TYPE_z1__zapiszProjekt (32)
/* complex XSD type 'z1:zapiszProjekt': */
struct z1__zapiszProjekt {
      public:
        /** Required element 'ID' of XSD type 'z1:id' */
        std::string ID;
        /** Optional element 'zapisywany' of XSD type 'z1:student' */
        z1__student *zapisywany;
      public:
        /** Return unique type id SOAP_TYPE_z1__zapiszProjekt */
        int soap_type() const { return SOAP_TYPE_z1__zapiszProjekt; }
        /** Constructor with member initializations */
        z1__zapiszProjekt()
        {
          zapisywany = (z1__student *)0;
        }
        /** Friend allocator used by soap_new_z1__zapiszProjekt(struct soap*, int) */
        friend SOAP_FMAC1 z1__zapiszProjekt * SOAP_FMAC2 soap_instantiate_z1__zapiszProjekt(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* zapisy.h:553 */
#ifndef SOAP_TYPE_z1__dodajProjektResponse
#define SOAP_TYPE_z1__dodajProjektResponse (33)
/* complex XSD type 'z1:dodajProjektResponse': */
struct z1__dodajProjektResponse {
      public:
        /** Required element 'rezultat' of XSD type 'z1:wynik' */
        std::string rezultat;
      public:
        /** Return unique type id SOAP_TYPE_z1__dodajProjektResponse */
        int soap_type() const { return SOAP_TYPE_z1__dodajProjektResponse; }
        /** Constructor with member initializations */
        z1__dodajProjektResponse()
        {
        }
        /** Friend allocator used by soap_new_z1__dodajProjektResponse(struct soap*, int) */
        friend SOAP_FMAC1 z1__dodajProjektResponse * SOAP_FMAC2 soap_instantiate_z1__dodajProjektResponse(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* zapisy.h:611 */
#ifndef SOAP_TYPE_z1__dodajProjekt
#define SOAP_TYPE_z1__dodajProjekt (37)
/* complex XSD type 'z1:dodajProjekt': */
struct z1__dodajProjekt {
      public:
        /** Optional element 'projekt' of XSD type 'z1:temat' */
        z1__temat *projekt;
      public:
        /** Return unique type id SOAP_TYPE_z1__dodajProjekt */
        int soap_type() const { return SOAP_TYPE_z1__dodajProjekt; }
        /** Constructor with member initializations */
        z1__dodajProjekt()
        {
          projekt = (z1__temat *)0;
        }
        /** Friend allocator used by soap_new_z1__dodajProjekt(struct soap*, int) */
        friend SOAP_FMAC1 z1__dodajProjekt * SOAP_FMAC2 soap_instantiate_z1__dodajProjekt(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* zapisy.h:622 */
#ifndef SOAP_TYPE_z1__zapiszTerminResponse
#define SOAP_TYPE_z1__zapiszTerminResponse (38)
/* complex XSD type 'z1:zapiszTerminResponse': */
struct z1__zapiszTerminResponse {
      public:
        /** Required element 'rezultat' of XSD type 'z1:wynik' */
        std::string rezultat;
      public:
        /** Return unique type id SOAP_TYPE_z1__zapiszTerminResponse */
        int soap_type() const { return SOAP_TYPE_z1__zapiszTerminResponse; }
        /** Constructor with member initializations */
        z1__zapiszTerminResponse()
        {
        }
        /** Friend allocator used by soap_new_z1__zapiszTerminResponse(struct soap*, int) */
        friend SOAP_FMAC1 z1__zapiszTerminResponse * SOAP_FMAC2 soap_instantiate_z1__zapiszTerminResponse(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* zapisy.h:683 */
#ifndef SOAP_TYPE_z1__zapiszTermin
#define SOAP_TYPE_z1__zapiszTermin (41)
/* complex XSD type 'z1:zapiszTermin': */
struct z1__zapiszTermin {
      public:
        /** Required element 'ID' of XSD type 'z1:id' */
        std::string ID;
        /** Optional element 'zapisywany' of XSD type 'z1:student' */
        z1__student *zapisywany;
      public:
        /** Return unique type id SOAP_TYPE_z1__zapiszTermin */
        int soap_type() const { return SOAP_TYPE_z1__zapiszTermin; }
        /** Constructor with member initializations */
        z1__zapiszTermin()
        {
          zapisywany = (z1__student *)0;
        }
        /** Friend allocator used by soap_new_z1__zapiszTermin(struct soap*, int) */
        friend SOAP_FMAC1 z1__zapiszTermin * SOAP_FMAC2 soap_instantiate_z1__zapiszTermin(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* zapisy.h:694 */
#ifndef SOAP_TYPE_z1__dodajTerminResponse
#define SOAP_TYPE_z1__dodajTerminResponse (42)
/* complex XSD type 'z1:dodajTerminResponse': */
struct z1__dodajTerminResponse {
      public:
        /** Required element 'rezultat' of XSD type 'z1:wynik' */
        std::string rezultat;
      public:
        /** Return unique type id SOAP_TYPE_z1__dodajTerminResponse */
        int soap_type() const { return SOAP_TYPE_z1__dodajTerminResponse; }
        /** Constructor with member initializations */
        z1__dodajTerminResponse()
        {
        }
        /** Friend allocator used by soap_new_z1__dodajTerminResponse(struct soap*, int) */
        friend SOAP_FMAC1 z1__dodajTerminResponse * SOAP_FMAC2 soap_instantiate_z1__dodajTerminResponse(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* zapisy.h:752 */
#ifndef SOAP_TYPE_z1__dodajTermin
#define SOAP_TYPE_z1__dodajTermin (46)
/* complex XSD type 'z1:dodajTermin': */
struct z1__dodajTermin {
      public:
        /** Optional element 'termin' of XSD type 'z1:termin' */
        z1__termin *termin;
      public:
        /** Return unique type id SOAP_TYPE_z1__dodajTermin */
        int soap_type() const { return SOAP_TYPE_z1__dodajTermin; }
        /** Constructor with member initializations */
        z1__dodajTermin()
        {
          termin = (z1__termin *)0;
        }
        /** Friend allocator used by soap_new_z1__dodajTermin(struct soap*, int) */
        friend SOAP_FMAC1 z1__dodajTermin * SOAP_FMAC2 soap_instantiate_z1__dodajTermin(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* zapisy.h:763 */
#ifndef SOAP_TYPE_z1__eksportujProjektResponse
#define SOAP_TYPE_z1__eksportujProjektResponse (47)
/* complex XSD type 'z1:eksportujProjektResponse': */
struct z1__eksportujProjektResponse {
      public:
        /** Required element 'nazwa' of XSD type 'z1:filename' */
        std::string nazwa;
        /** Required element 'plik' of XSD type 'z1:csv' */
        std::string plik;
      public:
        /** Return unique type id SOAP_TYPE_z1__eksportujProjektResponse */
        int soap_type() const { return SOAP_TYPE_z1__eksportujProjektResponse; }
        /** Constructor with member initializations */
        z1__eksportujProjektResponse()
        {
        }
        /** Friend allocator used by soap_new_z1__eksportujProjektResponse(struct soap*, int) */
        friend SOAP_FMAC1 z1__eksportujProjektResponse * SOAP_FMAC2 soap_instantiate_z1__eksportujProjektResponse(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* zapisy.h:822 */
#ifndef SOAP_TYPE_z1__eksportujProjekt
#define SOAP_TYPE_z1__eksportujProjekt (50)
/* complex XSD type 'z1:eksportujProjekt': */
struct z1__eksportujProjekt {
      public:
        /** Required element 'ID' of XSD type 'z1:id' */
        std::string ID;
      public:
        /** Return unique type id SOAP_TYPE_z1__eksportujProjekt */
        int soap_type() const { return SOAP_TYPE_z1__eksportujProjekt; }
        /** Constructor with member initializations */
        z1__eksportujProjekt()
        {
        }
        /** Friend allocator used by soap_new_z1__eksportujProjekt(struct soap*, int) */
        friend SOAP_FMAC1 z1__eksportujProjekt * SOAP_FMAC2 soap_instantiate_z1__eksportujProjekt(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* zapisy.h:833 */
#ifndef SOAP_TYPE_z1__eksportujTerminResponse
#define SOAP_TYPE_z1__eksportujTerminResponse (51)
/* complex XSD type 'z1:eksportujTerminResponse': */
struct z1__eksportujTerminResponse {
      public:
        /** Required element 'nazwa' of XSD type 'z1:filename' */
        std::string nazwa;
        /** Required element 'plik' of XSD type 'z1:csv' */
        std::string plik;
      public:
        /** Return unique type id SOAP_TYPE_z1__eksportujTerminResponse */
        int soap_type() const { return SOAP_TYPE_z1__eksportujTerminResponse; }
        /** Constructor with member initializations */
        z1__eksportujTerminResponse()
        {
        }
        /** Friend allocator used by soap_new_z1__eksportujTerminResponse(struct soap*, int) */
        friend SOAP_FMAC1 z1__eksportujTerminResponse * SOAP_FMAC2 soap_instantiate_z1__eksportujTerminResponse(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* zapisy.h:892 */
#ifndef SOAP_TYPE_z1__eksportujTermin
#define SOAP_TYPE_z1__eksportujTermin (54)
/* complex XSD type 'z1:eksportujTermin': */
struct z1__eksportujTermin {
      public:
        /** Required element 'ID' of XSD type 'z1:id' */
        std::string ID;
      public:
        /** Return unique type id SOAP_TYPE_z1__eksportujTermin */
        int soap_type() const { return SOAP_TYPE_z1__eksportujTermin; }
        /** Constructor with member initializations */
        z1__eksportujTermin()
        {
        }
        /** Friend allocator used by soap_new_z1__eksportujTermin(struct soap*, int) */
        friend SOAP_FMAC1 z1__eksportujTermin * SOAP_FMAC2 soap_instantiate_z1__eksportujTermin(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* zapisy.h:903 */
#ifndef SOAP_TYPE_z1__eksportujPrzedmiotResponse
#define SOAP_TYPE_z1__eksportujPrzedmiotResponse (55)
/* complex XSD type 'z1:eksportujPrzedmiotResponse': */
struct z1__eksportujPrzedmiotResponse {
      public:
        /** Required element 'nazwa' of XSD type 'z1:filename' */
        std::string nazwa;
        /** Required element 'plik' of XSD type 'z1:csv' */
        std::string plik;
      public:
        /** Return unique type id SOAP_TYPE_z1__eksportujPrzedmiotResponse */
        int soap_type() const { return SOAP_TYPE_z1__eksportujPrzedmiotResponse; }
        /** Constructor with member initializations */
        z1__eksportujPrzedmiotResponse()
        {
        }
        /** Friend allocator used by soap_new_z1__eksportujPrzedmiotResponse(struct soap*, int) */
        friend SOAP_FMAC1 z1__eksportujPrzedmiotResponse * SOAP_FMAC2 soap_instantiate_z1__eksportujPrzedmiotResponse(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* zapisy.h:962 */
#ifndef SOAP_TYPE_z1__eksportujPrzedmiot
#define SOAP_TYPE_z1__eksportujPrzedmiot (58)
/* complex XSD type 'z1:eksportujPrzedmiot': */
struct z1__eksportujPrzedmiot {
      public:
        /** Required element 'ID' of XSD type 'z1:id' */
        std::string ID;
      public:
        /** Return unique type id SOAP_TYPE_z1__eksportujPrzedmiot */
        int soap_type() const { return SOAP_TYPE_z1__eksportujPrzedmiot; }
        /** Constructor with member initializations */
        z1__eksportujPrzedmiot()
        {
        }
        /** Friend allocator used by soap_new_z1__eksportujPrzedmiot(struct soap*, int) */
        friend SOAP_FMAC1 z1__eksportujPrzedmiot * SOAP_FMAC2 soap_instantiate_z1__eksportujPrzedmiot(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* zapisy.h:1023 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (59)
/* SOAP_ENV__Header: */
struct SOAP_ENV__Header {
      public:
        /** Return unique type id SOAP_TYPE_SOAP_ENV__Header */
        int soap_type() const { return SOAP_TYPE_SOAP_ENV__Header; }
        /** Constructor with member initializations */
        SOAP_ENV__Header()
        {
        }
        /** Friend allocator used by soap_new_SOAP_ENV__Header(struct soap*, int) */
        friend SOAP_FMAC1 SOAP_ENV__Header * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Header(struct soap*, int, const char*, const char*, size_t*);
};
#endif
#endif

/* zapisy.h:1023 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (60)
/* Type SOAP_ENV__Code is a recursive data type, (in)directly referencing itself through its (base or derived class) members */
/* SOAP_ENV__Code: */
struct SOAP_ENV__Code {
      public:
        /** Optional element 'SOAP-ENV:Value' of XSD type 'xsd:QName' */
        char *SOAP_ENV__Value;
        /** Optional element 'SOAP-ENV:Subcode' of XSD type 'SOAP-ENV:Code' */
        struct SOAP_ENV__Code *SOAP_ENV__Subcode;
      public:
        /** Return unique type id SOAP_TYPE_SOAP_ENV__Code */
        int soap_type() const { return SOAP_TYPE_SOAP_ENV__Code; }
        /** Constructor with member initializations */
        SOAP_ENV__Code()
        {
          SOAP_ENV__Value = (char *)0;
          SOAP_ENV__Subcode = (struct SOAP_ENV__Code *)0;
        }
        /** Friend allocator used by soap_new_SOAP_ENV__Code(struct soap*, int) */
        friend SOAP_FMAC1 SOAP_ENV__Code * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Code(struct soap*, int, const char*, const char*, size_t*);
};
#endif
#endif

/* zapisy.h:1023 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (62)
/* SOAP_ENV__Detail: */
struct SOAP_ENV__Detail {
      public:
        char *__any;
        /** Any type of element 'fault' assigned to fault with its SOAP_TYPE_T assigned to __type */
        /** Do not create a cyclic data structure throught this member unless SOAP encoding or SOAP_XML_GRAPH are used for id-ref serialization */
        int __type;
        void *fault;
      public:
        /** Return unique type id SOAP_TYPE_SOAP_ENV__Detail */
        int soap_type() const { return SOAP_TYPE_SOAP_ENV__Detail; }
        /** Constructor with member initializations */
        SOAP_ENV__Detail()
        {
          __any = (char *)0;
          __type = 0;
          fault = NULL;
        }
        /** Friend allocator used by soap_new_SOAP_ENV__Detail(struct soap*, int) */
        friend SOAP_FMAC1 SOAP_ENV__Detail * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Detail(struct soap*, int, const char*, const char*, size_t*);
};
#endif
#endif

/* zapisy.h:1023 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (65)
/* SOAP_ENV__Reason: */
struct SOAP_ENV__Reason {
      public:
        /** Optional element 'SOAP-ENV:Text' of XSD type 'xsd:string' */
        char *SOAP_ENV__Text;
      public:
        /** Return unique type id SOAP_TYPE_SOAP_ENV__Reason */
        int soap_type() const { return SOAP_TYPE_SOAP_ENV__Reason; }
        /** Constructor with member initializations */
        SOAP_ENV__Reason()
        {
          SOAP_ENV__Text = (char *)0;
        }
        /** Friend allocator used by soap_new_SOAP_ENV__Reason(struct soap*, int) */
        friend SOAP_FMAC1 SOAP_ENV__Reason * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Reason(struct soap*, int, const char*, const char*, size_t*);
};
#endif
#endif

/* zapisy.h:1023 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (66)
/* SOAP_ENV__Fault: */
struct SOAP_ENV__Fault {
      public:
        /** Optional element 'faultcode' of XSD type 'xsd:QName' */
        char *faultcode;
        /** Optional element 'faultstring' of XSD type 'xsd:string' */
        char *faultstring;
        /** Optional element 'faultactor' of XSD type 'xsd:string' */
        char *faultactor;
        /** Optional element 'detail' of XSD type 'SOAP-ENV:Detail' */
        struct SOAP_ENV__Detail *detail;
        /** Optional element 'SOAP-ENV:Code' of XSD type 'SOAP-ENV:Code' */
        struct SOAP_ENV__Code *SOAP_ENV__Code;
        /** Optional element 'SOAP-ENV:Reason' of XSD type 'SOAP-ENV:Reason' */
        struct SOAP_ENV__Reason *SOAP_ENV__Reason;
        /** Optional element 'SOAP-ENV:Node' of XSD type 'xsd:string' */
        char *SOAP_ENV__Node;
        /** Optional element 'SOAP-ENV:Role' of XSD type 'xsd:string' */
        char *SOAP_ENV__Role;
        /** Optional element 'SOAP-ENV:Detail' of XSD type 'SOAP-ENV:Detail' */
        struct SOAP_ENV__Detail *SOAP_ENV__Detail;
      public:
        /** Return unique type id SOAP_TYPE_SOAP_ENV__Fault */
        int soap_type() const { return SOAP_TYPE_SOAP_ENV__Fault; }
        /** Constructor with member initializations */
        SOAP_ENV__Fault()
        {
          faultcode = (char *)0;
          faultstring = (char *)0;
          faultactor = (char *)0;
          detail = (struct SOAP_ENV__Detail *)0;
          SOAP_ENV__Code = (struct SOAP_ENV__Code *)0;
          SOAP_ENV__Reason = (struct SOAP_ENV__Reason *)0;
          SOAP_ENV__Node = (char *)0;
          SOAP_ENV__Role = (char *)0;
          SOAP_ENV__Detail = (struct SOAP_ENV__Detail *)0;
        }
        /** Friend allocator used by soap_new_SOAP_ENV__Fault(struct soap*, int) */
        friend SOAP_FMAC1 SOAP_ENV__Fault * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Fault(struct soap*, int, const char*, const char*, size_t*);
};
#endif
#endif

/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/


/* zapisy.h:102 */
#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
typedef char *_QName;
#endif

/* zapisy.h:102 */
#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (6)
typedef char *_XML;
#endif

/* zapisy.h:140 */
#ifndef SOAP_TYPE_xsd__integer
#define SOAP_TYPE_xsd__integer (12)
typedef std::string xsd__integer;
#endif

/* zapisy.h:143 */
#ifndef SOAP_TYPE_xsd__nonNegativeInteger
#define SOAP_TYPE_xsd__nonNegativeInteger (13)
typedef std::string xsd__nonNegativeInteger;
#endif

/* zapisy.h:185 */
#ifndef SOAP_TYPE_z1__godzina
#define SOAP_TYPE_z1__godzina (21)
typedef std::string z1__godzina;
#endif

/* zapisy.h:189 */
#ifndef SOAP_TYPE_z1__id
#define SOAP_TYPE_z1__id (22)
typedef xsd__integer z1__id;
#endif

/* zapisy.h:193 */
#ifndef SOAP_TYPE_z1__csv
#define SOAP_TYPE_z1__csv (23)
typedef xsd__integer z1__csv;
#endif

/* zapisy.h:197 */
#ifndef SOAP_TYPE_z1__filename
#define SOAP_TYPE_z1__filename (24)
typedef xsd__integer z1__filename;
#endif

/* zapisy.h:202 */
#ifndef SOAP_TYPE_z1__nrIndex
#define SOAP_TYPE_z1__nrIndex (25)
typedef std::string z1__nrIndex;
#endif

/* zapisy.h:207 */
#ifndef SOAP_TYPE_z1__wynik
#define SOAP_TYPE_z1__wynik (26)
typedef std::string z1__wynik;
#endif

/******************************************************************************\
 *                                                                            *
 * Serializable Types                                                         *
 *                                                                            *
\******************************************************************************/


/* char has binding name 'byte' for type 'xsd:byte' */
#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif

/* int has binding name 'int' for type 'xsd:int' */
#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif

/* z1__wynik has binding name 'z1__wynik' for type 'z1:wynik' */
#ifndef SOAP_TYPE_z1__wynik
#define SOAP_TYPE_z1__wynik (26)
#endif

/* z1__nrIndex has binding name 'z1__nrIndex' for type 'z1:nrIndex' */
#ifndef SOAP_TYPE_z1__nrIndex
#define SOAP_TYPE_z1__nrIndex (25)
#endif

/* z1__filename has binding name 'z1__filename' for type 'z1:filename' */
#ifndef SOAP_TYPE_z1__filename
#define SOAP_TYPE_z1__filename (24)
#endif

/* z1__csv has binding name 'z1__csv' for type 'z1:csv' */
#ifndef SOAP_TYPE_z1__csv
#define SOAP_TYPE_z1__csv (23)
#endif

/* z1__id has binding name 'z1__id' for type 'z1:id' */
#ifndef SOAP_TYPE_z1__id
#define SOAP_TYPE_z1__id (22)
#endif

/* z1__godzina has binding name 'z1__godzina' for type 'z1:godzina' */
#ifndef SOAP_TYPE_z1__godzina
#define SOAP_TYPE_z1__godzina (21)
#endif

/* z1__prowadzacy has binding name 'z1__prowadzacy' for type 'z1:prowadzacy' */
#ifndef SOAP_TYPE_z1__prowadzacy
#define SOAP_TYPE_z1__prowadzacy (20)
#endif

/* z1__typ has binding name 'z1__typ' for type 'z1:typ' */
#ifndef SOAP_TYPE_z1__typ
#define SOAP_TYPE_z1__typ (19)
#endif

/* z1__przedmiot has binding name 'z1__przedmiot' for type 'z1:przedmiot' */
#ifndef SOAP_TYPE_z1__przedmiot
#define SOAP_TYPE_z1__przedmiot (18)
#endif

/* z1__sala has binding name 'z1__sala' for type 'z1:sala' */
#ifndef SOAP_TYPE_z1__sala
#define SOAP_TYPE_z1__sala (17)
#endif

/* z1__termin has binding name 'z1__termin' for type 'z1:termin' */
#ifndef SOAP_TYPE_z1__termin
#define SOAP_TYPE_z1__termin (16)
#endif

/* z1__temat has binding name 'z1__temat' for type 'z1:temat' */
#ifndef SOAP_TYPE_z1__temat
#define SOAP_TYPE_z1__temat (15)
#endif

/* z1__student has binding name 'z1__student' for type 'z1:student' */
#ifndef SOAP_TYPE_z1__student
#define SOAP_TYPE_z1__student (14)
#endif

/* xsd__nonNegativeInteger has binding name 'xsd__nonNegativeInteger' for type 'xsd:nonNegativeInteger' */
#ifndef SOAP_TYPE_xsd__nonNegativeInteger
#define SOAP_TYPE_xsd__nonNegativeInteger (13)
#endif

/* xsd__integer has binding name 'xsd__integer' for type 'xsd:integer' */
#ifndef SOAP_TYPE_xsd__integer
#define SOAP_TYPE_xsd__integer (12)
#endif

/* std::string has binding name 'std__string' for type 'xsd:string' */
#ifndef SOAP_TYPE_std__string
#define SOAP_TYPE_std__string (11)
#endif

/* struct SOAP_ENV__Fault has binding name 'SOAP_ENV__Fault' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (66)
#endif

/* struct SOAP_ENV__Reason has binding name 'SOAP_ENV__Reason' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (65)
#endif

/* struct SOAP_ENV__Detail has binding name 'SOAP_ENV__Detail' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (62)
#endif

/* struct SOAP_ENV__Code has binding name 'SOAP_ENV__Code' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (60)
#endif

/* struct SOAP_ENV__Header has binding name 'SOAP_ENV__Header' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (59)
#endif

/* struct z1__eksportujPrzedmiot has binding name 'z1__eksportujPrzedmiot' for type 'z1:eksportujPrzedmiot' */
#ifndef SOAP_TYPE_z1__eksportujPrzedmiot
#define SOAP_TYPE_z1__eksportujPrzedmiot (58)
#endif

/* struct z1__eksportujPrzedmiotResponse has binding name 'z1__eksportujPrzedmiotResponse' for type 'z1:eksportujPrzedmiotResponse' */
#ifndef SOAP_TYPE_z1__eksportujPrzedmiotResponse
#define SOAP_TYPE_z1__eksportujPrzedmiotResponse (55)
#endif

/* struct z1__eksportujTermin has binding name 'z1__eksportujTermin' for type 'z1:eksportujTermin' */
#ifndef SOAP_TYPE_z1__eksportujTermin
#define SOAP_TYPE_z1__eksportujTermin (54)
#endif

/* struct z1__eksportujTerminResponse has binding name 'z1__eksportujTerminResponse' for type 'z1:eksportujTerminResponse' */
#ifndef SOAP_TYPE_z1__eksportujTerminResponse
#define SOAP_TYPE_z1__eksportujTerminResponse (51)
#endif

/* struct z1__eksportujProjekt has binding name 'z1__eksportujProjekt' for type 'z1:eksportujProjekt' */
#ifndef SOAP_TYPE_z1__eksportujProjekt
#define SOAP_TYPE_z1__eksportujProjekt (50)
#endif

/* struct z1__eksportujProjektResponse has binding name 'z1__eksportujProjektResponse' for type 'z1:eksportujProjektResponse' */
#ifndef SOAP_TYPE_z1__eksportujProjektResponse
#define SOAP_TYPE_z1__eksportujProjektResponse (47)
#endif

/* struct z1__dodajTermin has binding name 'z1__dodajTermin' for type 'z1:dodajTermin' */
#ifndef SOAP_TYPE_z1__dodajTermin
#define SOAP_TYPE_z1__dodajTermin (46)
#endif

/* struct z1__dodajTerminResponse has binding name 'z1__dodajTerminResponse' for type 'z1:dodajTerminResponse' */
#ifndef SOAP_TYPE_z1__dodajTerminResponse
#define SOAP_TYPE_z1__dodajTerminResponse (42)
#endif

/* struct z1__zapiszTermin has binding name 'z1__zapiszTermin' for type 'z1:zapiszTermin' */
#ifndef SOAP_TYPE_z1__zapiszTermin
#define SOAP_TYPE_z1__zapiszTermin (41)
#endif

/* struct z1__zapiszTerminResponse has binding name 'z1__zapiszTerminResponse' for type 'z1:zapiszTerminResponse' */
#ifndef SOAP_TYPE_z1__zapiszTerminResponse
#define SOAP_TYPE_z1__zapiszTerminResponse (38)
#endif

/* struct z1__dodajProjekt has binding name 'z1__dodajProjekt' for type 'z1:dodajProjekt' */
#ifndef SOAP_TYPE_z1__dodajProjekt
#define SOAP_TYPE_z1__dodajProjekt (37)
#endif

/* struct z1__dodajProjektResponse has binding name 'z1__dodajProjektResponse' for type 'z1:dodajProjektResponse' */
#ifndef SOAP_TYPE_z1__dodajProjektResponse
#define SOAP_TYPE_z1__dodajProjektResponse (33)
#endif

/* struct z1__zapiszProjekt has binding name 'z1__zapiszProjekt' for type 'z1:zapiszProjekt' */
#ifndef SOAP_TYPE_z1__zapiszProjekt
#define SOAP_TYPE_z1__zapiszProjekt (32)
#endif

/* struct z1__zapiszProjektResponse has binding name 'z1__zapiszProjektResponse' for type 'z1:zapiszProjektResponse' */
#ifndef SOAP_TYPE_z1__zapiszProjektResponse
#define SOAP_TYPE_z1__zapiszProjektResponse (28)
#endif

/* struct SOAP_ENV__Reason * has binding name 'PointerToSOAP_ENV__Reason' for type '' */
#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (68)
#endif

/* struct SOAP_ENV__Detail * has binding name 'PointerToSOAP_ENV__Detail' for type '' */
#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (67)
#endif

/* struct SOAP_ENV__Code * has binding name 'PointerToSOAP_ENV__Code' for type '' */
#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (61)
#endif

/* z1__termin * has binding name 'PointerToz1__termin' for type 'z1:termin' */
#ifndef SOAP_TYPE_PointerToz1__termin
#define SOAP_TYPE_PointerToz1__termin (43)
#endif

/* z1__temat * has binding name 'PointerToz1__temat' for type 'z1:temat' */
#ifndef SOAP_TYPE_PointerToz1__temat
#define SOAP_TYPE_PointerToz1__temat (34)
#endif

/* z1__student * has binding name 'PointerToz1__student' for type 'z1:student' */
#ifndef SOAP_TYPE_PointerToz1__student
#define SOAP_TYPE_PointerToz1__student (29)
#endif

/* _XML has binding name '_XML' for type '' */
#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (6)
#endif

/* _QName has binding name '_QName' for type 'xsd:QName' */
#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif

/* char * has binding name 'string' for type 'xsd:string' */
#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif

/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


#endif

/* End of soapStub.h */
